[package]
name = "i2ray"
version = "0.1.0"
edition = "2018"


[dependencies]
tokio = { version = "1", features = ["full"] }
byteorder = "1"
rust-crypto = "0.2"
rand = "0.8.4"

[dev-dependencies]
env_logger = "0.9.0"